version: 2.1.{build}
image: Visual Studio 2017
init:
- ps: Install-Product node $env:nodejs_version
environment:
  matrix:
  - PACKAGE_TASK: package-win32
    platform: x64
    nodejs_version: 10
install:
- pwsh: npm install --no-optional --no-shrinkwrap --no-package-lock
cache:
- node_modules
- '%APPDATA%\npm-cache'
build_script:
- pwsh: "$package_list = Get-ChildItem \"*.7z\"\nforeach($package in $package_list) { \n    $package_name = $package.Name\n    Remove-Item -Force \"$package_name\"\n}\nnpm run $ENV:PACKAGE_TASK\ncd out\n$package_list = Get-ChildItem\nforeach($package in $package_list) { \n    $package_name = $package.Name\n    echo \"$package_name\"\n    7z a -y -r \"../$package_name.7z\" \"$package_name\"\n}"
artifacts:
- path: '*.7z'
  name: release-package
deploy:
- provider: GitHub
  auth_token:
    secure: dIpxVrO8JURzr07RBbYkmBYRo2S3+88DlPuPD1aJS3nJivC3kgWYp+rRHnRr71qb
  repository: xresloader/xresconv-gui
  artifact: release-package
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true