environment:
  nodejs_version: "10"

version: 1.0.{build}

image: Visual Studio 2017

matrix:
  - PACKAGE_TASK: package-win32

platform:
  - x64

install:
- ps: >-
    Install-Product node $env:nodejs_version

    & npm install --force

cache: C:\Users\appveyor\.cargo\registry
build_script:
- ps: >-
    $package_list = Get-ChildItem "*.7z"

    foreach($package in $package_list) { 
      
      $package_name = $package.Name

      Remove-Item -Force "$package_name"

    }

    & npm run $ENV:PACKAGE_TASK

    cd out

    $package_list = Get-ChildItem

    foreach($package in $package_list) { 
      
      $package_name = $package.Name

      echo "$package_name"

      if (Test-Path "../$package_name.7z") {
        Remove-Item -Force "../$package_name.7z"
      }
      
      & 7z a -y -r "../$package_name.7z" "$package_name"

    }

artifacts:
- path: '*.7z'
  name: release-package

deploy:
- provider: GitHub
  auth_token:
    secure: dIpxVrO8JURzr07RBbYkmBYRo2S3+88DlPuPD1aJS3nJivC3kgWYp+rRHnRr71qb
  artifact: release-package
  force_update: true
  draft: true
  on:
    APPVEYOR_REPO_TAG: true 